export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored just for You",
        description: "Get interview questions and nodel answers based on your role, experience, and specific focus areas - no generic parctice here.",
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: "Expand answers only where you're ready. Dive deeper into any concept instantly with AI-powered detailed instantly with AI-powered detailed explanations.",
    },
    {
        id: "03",
        title: "Capture Your Insights",
        description: "Add personal notes to any question and pin important ones to the top - making your learning more organized and powerful.",
    },
    {
        id: "04",
        title: "Understand the 'Why' Behind Answers",
        description: "Beyind just answers - unlock detailed concept explanations generated by AI, helping you truly master each topic.",
    },
    {
        id: "05",
        title: "Save, Organize and Revisit",
        description: "Easily save your interview sets, organize them meatly in your dashboard, and pick your preparation right when you left off.",
    },
];